# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a28f7f3bddddaf7534a9b0f9aad1141c577f0a06b5a59681f2ae06d5fe8770d686a8859ec0748f782abd5e936572a19db3c1d7480a2b6accdc7f5636ff52fc2

test:
  secret_key_base: c17268fc1f20693f918f04834d1275385eab46b54e0cf5b20a5f0e93c0b09f893e1935212dc3ba6cc4ab4ce9d48b4f59deed5e0ec1490617f7998372853c4bfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
